//this is used as list for getting the numerous cryto curriences used by the api

export let cryptoCurrencies = [
    '0x',
    'ATMChain',
    'AdEx',
    'Aeternity',
    'Aragon',
    'Ardor',
    'Ark',
    'Augur',
    'Bancor',
    'Basic Attenti...',
    'Binance Coin',
    'BitConnect',
    'BitShares',
    'Bitcoin',
    'Bitcoin Cash',
    'BitcoinDark',
    'Bitdeal',
    'Bitquence',
    'Blocknet',
    'Byteball Bytes',
    'Bytecoin',
    'Bytom',
    'Cardano',
    'ChainLink',
    'Civic',
    'Dash',
    'Decred',
    'Dentacoin',
    'DigiByte',
    'DigixDAO',
    'Dogecoin',
    'EOS',
    'Edgeless',
    'Ethereum',
    'Ethereum Classic',
    'Factom',
    'FirstCoin',
    'FunFair',
    'GXShares',
    'GameCredits',
    'Gas',
    'Gnosis',
    'Golem',
    'Hshare',
    'I/O Coin',
    'IOTA',
    'Iconomi',
    'Kin',
    'Komodo',
    'Kyber Network',
    'Lisk',
    'Litecoin',
    'Loopring',
    'Lykke',
    'MCAP',
    'MaidSafeCoin',
    'Metal',
    'Metaverse ETP',
    'MonaCoin',
    'Monaco',
    'Monero',
    'NAV Coin',
    'NEM',
    'NEO',
    'Neblio',
    'Nexus',
    'NoLimitCoin',
    'Nxt',
    'OmiseGO',
    'PIVX',
    'Particl',
    'Populous',
    'Pura',
    'Qtum',
    'Ripple',
    'SALT',
    'Siacoin',
    'SingularDTV',
    'SmartCash',
    'Status',
    'Steem',
    'Stellar Lumens',
    'Storj',
    'Stratis',
    'Syscoin',
    'TRON',
    'TaaS',
    'TenX',
    'Tether',
    'Ubiq',
    'VeChain',
    'Verge',
    'Veritaseum',
    'Vertcoin',
    'Walton',
    'Waves',
    'ZCoin',
    'Zcash',
    'ZenCash',
    'iExec RLC'
  ];